### ISSUE TITLE
Support for Uncore frequency?

### ISSUE THREAD

**Issue by d4k0** [RRZE-HPC/pylikwid#10]
Hi,

Would it be possible to add support for the Uncore frequency? In particular it would be nice to query the max/min/current frequency and to set it. The C API already supports all of this, but the Python API currently only allows to query if the processor has Uncore support.

**Comment by TomTheBear** [comment]
Sure, as soon as I have time, I'll add the functions.

**Comment by TomTheBear** [comment]
Added in https://github.com/RRZE-HPC/pylikwid/commit/672e3dbed31084d75711a769f756d11fbb4755ff

**Comment by d4k0** [comment]
Thanks for the fast implementation! Unfortunately, I now get this error when I run any of the tests:

```
$ ./testtopo.py 
Traceback (most recent call last):
  File "./testtopo.py", line 3, in <module>
    import pylikwid
ImportError: /home/user/.local/lib/python2.7/site-packages/pylikwid.so: undefined symbol: freq_getUncoreFreqCur
```

If I install version 0.2.7, the tests work again (of course `testfreq.py` then complains that the new functions are not known).

**Comment by TomTheBear** [comment]
The function `freq_getUncoreFreqCur` was added after the release of version 4.3.2 . It's only in the master branch. I'll remove that function again and add it after the next release of LIKWID.
