### ISSUE TITLE
error while importing pylikwid

### ISSUE THREAD

**Issue by archi456** [RRZE-HPC/pylikwid#17]
I have installed pylikwid both manually and using pip in linux . But whenever I am trying to import pylikwid , it is showing: ImportError: liblikwid.so.5.1: cannot open shared object file: No such file or directory

Note: There is no error while I am installing pylikwid (both manual and pip). 

how to solve this issue?

**Comment by TomTheBear** [comment]
You can specify the path to LIKWID with `LIKWID_PREFIX` for the pylikwid installation like
`export LIKWID_PREFIX=/usr/mylocal`. It searchs for the LIKWID library in `/usr/mylocal/lib`. This path should be part of the `LD_LIBRARY_PATH` while execution.

The other possibility could be a version clash. During installation, it finds LIKWID 5.1.x but, at runtime, there is only a 5.2.x library. You can also use the `LIKWID_PREFIX` to tell pylikwid where the 5.2.x library is located.

**Comment by archi456** [comment]
Hi .. The error is now resolved , it was path related. Thanks for your help.
